### ISSUE TITLE
synchronize issues

### ISSUE THREAD

**Issue by thewayur** [cocktailpeanut/breadmachine#9]
while scynchronising SDA1111 folder around 8GBs (with very long file names), 
breadmachine stops with below error:

`
node:internal/fs/promises:899
  const result = await binding.stat(pathModule.toNamespacedPath(path),
                               ^

Error: ENOENT: no such file or directory, stat
    at Object.stat (node:internal/fs/promises:899:32)
    at Object.sync (D:\node_apps\breadboard-web\node_modules\breadmachine\ipc.js:133:42)
    at async IPC.call (D:\node_apps\breadboard-web\node_modules\breadmachine\ipc.js:193:13)
    at async D:\node_apps\breadboard-web\node_modules\breadmachine\index.js:356:15 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat'
}
`

![image](https://github.com/cocktailpeanut/breadmachine/assets/2944767/f3f77dd1-8f7b-4ab8-81f6-74873e3a7fcd)

 

comfyui folders are doing great (has short names).

**_this problem does not occurs in breadboard_**

**Comment by thewayur** [comment]
ok after lots of hit and trials (testing chunks of folders), i narrowed down to 1 culprit file.
it had emoji in filename =
`summer, brown eyes, 😨, ,.png`
![image](https://github.com/cocktailpeanut/breadmachine/assets/2944767/d6f7c21f-0dfd-44bf-928b-ea6e2b8aefd8)

so after removing emoji from filename =
` summer, brown eyes, , ,.png`
![image](https://github.com/cocktailpeanut/breadmachine/assets/2944767/6d1c08ea-47b0-493f-a9ff-e259aff8bf99)

now everything is fine.

**i request developers to  find a solution for unsupported filenames** , therefore i am keeping this issue open. u can close this issue after noticing.

Thanks for such an awesome app.
love from India <3

**Comment by thewayur** [comment]
FOR DEVELOPERS:

### if filename has emoji(in my case) or unsupported  characters. app sync stops with error
fix it please.

u can close this issue after noticing,
